### ISSUE TITLE
Hacer que parezca fija la torreta

### ISSUE THREAD

**Issue by nicofo** [NestorTejero/ES2016A#100]

**Comment by sgarriga10** [comment]
Definition of Done:
- Creación de una base para el avión, de tal manera que fije el avión al suelo.
- Texturas de la base.
- Animaciones del avión con la nueva base.

**Comment by carlosarenasf** [comment]
Definition of Done:

- Creación de una base para el tanque de tal manera que quede fijo al suelo.

- Texturas de la base.

- Separar la base del tanque de el cañon para que puedan integrarse por separado en unity.

- Animación con la base fija al suelo.

**Comment by sgarriga10** [comment]
Issue Done.

**Comment by sgarriga10** [comment]
Se ha creado correctamente la base y se ha arreglado un bug a la hora de aplicar la textura(4h).

Se ha arreglado un bug por el que no se podía mostrar correctamente la animación anterior en unity. Se ha generado correctamente una nueva animación en un modelo diferente al de la base para facilitar la integración a los programadores. (3h).

Al acabar con antelación mi issue, estuve haciendo textura de sangre (issue añadida a este sprint pero se añadirá para el siguiente sprint). No he logrado acabarla, queda pendiente acabarla para el siguiente sprint. (1h).

**Comment by carlosarenasf** [comment]
Se ha creado la base del tanque, dividiendo el tanque en dos partes, una será móvil y la otra no.
Esto ha conllevado rehacer de nuevo la animación y texturas.
La división del tanque más la base han sido 3h ya que he tenido problemas para dividirlo.
La animación han sido 3h ya que he tenido problemas a la hora de dividirlo.
Las texturas me han llevado 2h ya que me daba problemas con los vértices a la hora de hacer el pintado de las mismas.
