### ISSUE TITLE
Diferentes modelos para mostrar la destruccion de la torre de colom

### ISSUE THREAD

**Issue by nicofo** [NestorTejero/ES2016A#101]

**Comment by vmganela** [comment]
DEFINITION OF DONE: 
1. Multiples archivos.
2. Medidas Correctas
3. Reset de localizacion
4. Con las Mismas Texturas y mapeados
5. Nombres Correctos
6. Normales con direccion correcta(hacia fuera de la figura)
7. Hacer el UVMapping de todos los modelos (sin corte)
8. Retocar Smoothing Groups
9. Deterioro por textura ademas de forma
10. Quiter Vertices internos

**Comment by vmganela** [comment]
Se han creado 4 torretas (2 veces), esto es debido a que tuve que rehacer los modelos, ya que en el modelo de la torre completa anterior las texturas, los nombres y la dirección de las normales no estaba bien,retocar los vértices y planes para seleccionar cuales serán suavizado, la codificación de nombre y reset de localizaciones.


Sinceramente era más rápido hacerlo en la torre completa y luego rehacer las torres rotas.


La mayor parte del tiempo de este sprint fue encontrar la forma más rápida para hacer las 4 torres. esto fue durante los primeros días de la primera semana del sprint, para así tenerlo listo durante el sprint review me llevó alrededor de 3 horas.


En la creación de la segunda torres se llevó bastante de mi tiempo todos las partes para hacer el definition of done, la gran mayoría de cosas eran rápidas de hacer, pero 3 partes son las que se llevaron parte de mi tiempo, Retocar Smoothing Groups,Hacer el UVMapping de todos los modelos (sin corte, seamless), creacion de las 4 torres  y la oclusión ambiental.


Hacer  bueno la figura y selección de caras y vértices fue más largo de los esperado 30 minutos, para dejarlo todo perfecto, Eliminar las líneas de costura fue muy complicado y muy laborioso, creo que me llevo una media hora tener la idea de como hacer y 2 horas hacerlo. Estas 2 partes solo tuve que hacerlo solo una vez en la torre original.


Luego con todo correcto cree las 4 torres diferentes que me llevó medio hora hacerlas.
Luego la oclusión ambiental  tarde una hora y media, y tras esto yo ya habia terminado, utilice el resto del tiempo que tenía para exportar y revisar en cada torre individualmente que cumpliera el DOD

**Comment by NestorTejero** [comment]
estat tancat?

**Comment by aoflus** [comment]
La tasca està acabada. He parlat amb el Victor i tinc el seu permís per tancar la issue. Perdona les molèsties.
