### ISSUE TITLE
Mejoras del modelo Porky y integración del cavernicola

### ISSUE THREAD

**Issue by nicofo** [NestorTejero/ES2016A#102]

**Comment by aoflus** [comment]
Definition of Done: 
- Personaje cavernícola integrado totalmente en el modelo del cerdo.
- Animaciones de movimiento, ataque, y muerte.
- Integración y comprovación en un proyecto de unity.

**Comment by aoflus** [comment]
The caveman has been integrated, added also a saddle for the caveman. (4h).
The animations and final textures are yet to be done. Expected time: 4 hours.

**Comment by aoflus** [comment]
There are some issues with the textures. The integrating team has beed already advised, that the model might change during tomorrow.

**Comment by aoflus** [comment]
The issues with the textures have been solved. (6h)
Added the movement and attack animations to the model. (3h)
The model has been tested on personal environment. Needs to be tested by the integration team prior to deployment. I will be given feedback tomorrow.

**Comment by nicofo** [comment]
El modelo ha sido integrado. De momento no hay ningun problema visual. 
Probablemente haya algun problema con las animaciones. Mañana confirmamos.

**Comment by aoflus** [comment]
The "Death" animation is yet to be done. It has been decided to leave this part of the issue for the next sprint, as it is the less important.

**Comment by NestorTejero** [comment]
estat tancat?

**Comment by aoflus** [comment]
En un principi pensavem que no ho estava, però després de la xerrada de retrospective, on es va decidir que no s'implementaria l'animació de mort del personatge. Per tant la issue està complerta. Procedeixo a tancarla.
