### ISSUE TITLE
Nuevo modelo de torreta

### ISSUE THREAD

**Issue by nicofo** [NestorTejero/ES2016A#103]
Condition of done: Una torre simple. Con textura. Que cumpla las medidas de "Game mesures" (6m x 6m x 10m)

**Comment by ezendirak** [comment]
![tower-torrepiedra](https://cloud.githubusercontent.com/assets/17324835/20565982/daa51af6-b193-11e6-8022-c762daacad81.PNG)

**Comment by nicofo** [comment]
He revisado el modelo. Estan bien.
Solo hay problemas en las direcciones y nombres de archivos. 
Habria que cambiarle el nombre al archivo y la textura deberia ir en la carpeta 'buildings' en vez de en 'Enemis'.

**Comment by NestorTejero** [comment]
estat?

**Comment by aoflus** [comment]
He hablado con Pol, la issue está acabada. Procedo a cerrarla con permiso suyo.
