### ISSUE TITLE
Cambiar el nombre de los archivos segun las nuevas convenciones(ver wiki)

### ISSUE THREAD

**Issue by nicofo** [NestorTejero/ES2016A#104]
Leer wiki

**Comment by aoflus** [comment]
Definition of Done:
- Nombre de TODOS los modelos .blend y .fbx cambiados segun la nomenclatura:
  - tower-nombre
  - enemy-nombre
- Seguir el mismo proceso para las texturas y sonidos.
- Si hay algún material creado, seguir el mismo procedimiento.

**Comment by sgarriga10** [comment]
Done.

**Comment by sgarriga10** [comment]
Definition of Done:

Nombre de TODOS los modelos .blend y .fbx cambiados segun la nomenclatura:
tower-nombre
texturas y sonidos: tower-nombre
Eliminar modelos antiguos que no se utilizan.

**Comment by sgarriga10** [comment]
Se han modificado correctamente y subido todos los archivos respetando la nueva nomenclatura. 

Se han eliminado todos los modelos que contenian versiones anteriores y que no se utilizaban.

**Comment by aoflus** [comment]
Moved the issue to the "Review" column, waiting for the review and retrospective to see if it can be moved to the "Done" column.
