### ISSUE TITLE
Create a 'Back to main menu' option

### ISSUE THREAD

**Issue by wj127** [NestorTejero/ES2016A#108]
The user, when exiting the current game/match, should be redirected back to the main menu, again, instead of finishing the whole game as happens now!

**Comment by emiralles** [comment]
Done: Opción dentro del juego que permite al usuario retornar al inicio del juego para modificar o empezar de nuevo la partida.

Se ha creado un nuevo botón con la funcionalidad que permite al usuario en cualquier momento mediante el menú de pause poder retornar al inicio del juego.
