### ISSUE TITLE
Show a 'Game Over' state

### ISSUE THREAD

**Issue by wj127** [NestorTejero/ES2016A#112]
Show to the user he/she is in a 'Game Over' state, giving the option to restart the match once again!

**Comment by emiralles** [comment]
Done. Cuando el juego haya terminado aparecerá la pantalla de game over del juego con las opciones que permita o acabar el juego o retornar al inicio para poder volver a jugar.

Se ha realizado la escena que contiene las opciones descritas en Done para los efectos de uso por parte del usuario.
