### ISSUE TITLE
Organize/Fix Problems/Integrate

### ISSUE THREAD

**Issue by wj127** [NestorTejero/ES2016A#120]
**Definition of Done (DoD)**:
- Organize every branch per issue created, into a single one, keeping the control over the project, an avoiding conflicts.
- Summarize all the issues into one branch (dev_TeamC), and merge it to de main one (dev) once we all are done.
- Fix all the problems generated by the last massive merge/integration of all the main branches of every team, which erased some work made by this team (C). 
- Enhance some features generated by the same problem mentioned above.
- Control the team work. It means, everyone made his work correctly, without disturbing or breaking the work of the other.
- Fix mainMenu Music and Mute lastSprint by @raulgb

**Comment by edgarllorente** [comment]
- Restored all code lost on last integration. (GUI Logic Code)
- Restored pause button.
- Restored setting menu's mute buttons.
- Restored InGame and Pause Menu music.
