### ISSUE TITLE
Add difficulty levels

### ISSUE THREAD

**Issue by dannylarrea** [NestorTejero/ES2016A#129]
Round configuration and enemy stats must be adjusted so that player experiences increasing difficulty.

PREREQUISITES: Following issues will dramatically change current game balance, and so this issue sould not
be taken if the following have not reached DONE:
- issue #164 will change the way enemies interact with the player.
- issue #162 will improve tower performance.
- issue #161 will probably worsen tower performance.

**Comment by dannylarrea** [comment]
Choose the number of levels with the team C, to add level buttons

**Comment by edgarllorente** [comment]
El equipo C propone 3 niveles, fácil, medio y difícil.

**Comment by mgonzafe91** [comment]
**DoD:** Por parte del Team B añadiremos un xml de rondas para cada dificultad (se ha decidido que 3)

La idea es que el jugador pueda seleccionar la dificultad antes de empezar la partida y no poderse modificar dentro de la partida (aunque se puede dejar tal como está en los settings de la partida solo que remarcando la dificultad elegida y bloquear las otras dos).
Necesitaría poder recibir la dificultad elegida (del LogicConnector mismo) para seleccionar un xml o otro.

**Comment by mgonzafe91** [comment]
Estado actual:

Ya existe un xml por dificultad y son llamados correctamente.

![image](https://cloud.githubusercontent.com/assets/9026825/21064835/7a21093e-be5d-11e6-943a-3897d8c627ad.png)

![image](https://cloud.githubusercontent.com/assets/9026825/21064907/dee89a94-be5d-11e6-9761-766e39a2d7d3.png)



Falta recibir un string de la dificultad desde el LogicConnector. Las opciones son "easy", "medium" o "hard". Se deberá modificar la asignación de difficulty a un método del LogicConnector (Team C)

![image](https://cloud.githubusercontent.com/assets/9026825/21064926/fbe79712-be5d-11e6-96db-3e0e1c5fc26f.png)

**Comment by sdiaz7** [comment]
Branch merged into DEV. Any inconsistencies will be adressed at #220 . Issue closed and moved to DONE.
