### ISSUE TITLE
Add the first tower model

### ISSUE THREAD

**Issue by dannylarrea** [NestorTejero/ES2016A#130]

**Comment by agonzatr17** [comment]
Done in issue "Fix bugs Sprint 3" #131, referenced above

**Comment by NestorTejero** [comment]
milestone? definition of done?

**Comment by agonzatr17** [comment]
**Problem**: the 1st tower button was not placing a visible tower.

**Definition of DONE**: the 1st tower button places a tower prefab with a visible model.
