### ISSUE TITLE
Fix bugs Sprint 3

### ISSUE THREAD

**Issue by mgonzafe91** [NestorTejero/ES2016A#131]
Solucionar todos los bugs de implementación antes de empezar el sprint 4

Problemas que surgieron durante la integración del Sprint 3:

TODO:
- Los enemigos no se desplazan correctamente por el mapa (animaciones y orientar hacia la estatua).
**Asignado:** -
- La opción de vender/mejorar torres no funciona. Los prefabs de torre están mal etiquetados. (Solo falta la opción de mejorar)
**Asignado:** Sergi Díaz
- Tamaño porky no concuerda con https://github.com/NestorTejero/ES2016A/wiki/Game%20Measures.
**Asignado:** -
- Añadir proyectiles a las torres (tienen el proyectil por defecto)
**Asignado:** -
- Funcionalidad del boton Start? Debe llamar al método NextRound() de ControlWaves
**Asignado:** -

Para arreglar en otra issue: Los enemigos al llegar a la estatua desaparecen. En vez de eso, añadir animación de ataque y que reduzca la vida de la estatua

TO REVIEW:
- Comprobar que todos los nombres y rutas de los modelos, texturas, sonidos sigan el documento de https://github.com/NestorTejero/ES2016A/wiki/Naming%20Conventions
- A los prefabs de enemigo les faltan los componentes mínimos necesarios para su correcto funcionamiento.
- Al prefab de torre simple (la torre dinosaurio) no tiene un modelo asignado. Resolución a parte, ya hay una issue assignada: #130 
- La colocación de torres ha dejado de funcionar correctamente: ya no se impide la colocación en terreno impasable. La torre con avión aparece elevada sobre el terreno. 
- Arreglar el zoom de la cámara.
- Los enemigos no esquivan torres/obstaculos
- No se puede colocar torres en la parte superior de la pantalla. (sigue bug al colocar torre en HUD inferior)
- Los enemigos colisionan con la torre antes de colocarla
- Se puede bloquear el paso a los enemigos y no llegan a la estatua
- La torre de Colón no recibe daño de los enemigos.

DONE: Juego funcional

El trabajo de esta issue se desarrolla en la rama dev_FixBugs: https://github.com/NestorTejero/ES2016A/tree/dev_FixBugs

**Comment by sdiaz7** [comment]
Bug 4 - algunas torres aparecen elevadas sobre el terreno 
Bug 5 - los prefabs de torre no estan etiquetadas como "tower"

**Comment by sdiaz7** [comment]
Bug de venta de torre arreglado.

Las torres formadas por mas de una pieza guardan el script de TowerBehaviour en la parte móvil (la que dispara). Si se intenta acceder al behavior usando la función GetComponent del GameObject torre esta devuelve NULL (no encuentra el componente). Para poder acceder al componente hay que usar la función **GetComponentInChildren**.

**Comment by mgonzafe91** [comment]
Bug de torres arreglado.

Al colocar una torre ahora usa la altura del prefab en vez de una "altura a ojo". Se arregló problemas con tags y componentes que fallaban durante la ejecución.

**Comment by ezendirak** [comment]
He modificado los nombres de las texturas y de una torre que no cumplían el names convention.
He eliminado modelos antiguos que ya no usamos y que eran de pruebas o están deprecados actualmente.
Actualmente tenemos 3 tropas y 4 torres (2 de ataque mas la central).

**Comment by sdiaz7** [comment]
Arreglado zoom de la cámara.

También he modificado su comportamiento para que solo pueda desplazarse por un espacio limitado (definible desde el Inspector). También he añadido una función para centrar la vista de la cámara en un objeto o una posición. De momento solo se usa para centrar la cámara sobre la torre de Colón al inicio de la partida.

**Comment by mgonzafe91** [comment]
Arreglado problema del Nav.

Los enemigos no esquivaban las torres porque faltaba activar la opción de "carve". También había problemas con el terreno y pasaban por encima del río pero ya se ajustó el bake.

**Comment by dannylarrea** [comment]
Arreglado el problema de adaptación del HUD al tamaño de la pantalla.

Cada vez que se cambie el tamaño de la pantalla se actualiza la posición del HUD inferior, esto permite la correcta colocación de torres.

**Comment by mgonzafe91** [comment]
Ya no se puede bloquear el paso a enemigos. Si el enemigo no puede moverse en 3 segundos destruye torres de alrededor. A veces se bugea el enemigo y después de destruir las torres no se mueve o da vueltas.

**Comment by sdiaz7** [comment]
La torre de Colón ya recibe daño.

He modificado el modo por el que se asigna el daño. Hasta ahora, cuando la torre detectaba una colisión comprobaba si esta había sido con un objeto "enemy", y de ser así disminuía su propia salud. Ahora, la torre ya no comprueba el choque. Cuando un enemigo detecta que ha colisionado con el objeto "home" le ordena a éste que pierda vida. La asignación del daño pasa a controlarla el enemigo.

**Comment by sdiaz7** [comment]
Tras el último commit parece que los enemy-gordo aparecen correctamente. Si a alguien le dan algún problema que avise.

**Comment by sdiaz7** [comment]
Ya se han arreglado los bugs más graves y el juego vuelve a ser funcional. Tal vez sería hora de dar por finalizada la issue y mergear con dev, de modo que los tres equipos podamos empezar a trabajar en el resto de issues.
De ser así, se añadirían algunas tareas para este sprint:

- Revisar los modelos de enemy, asegurarse que están bien orientados, tienen el tamaño correcto, etc.
- Corregir la animación de enemy-gordo.

**Comment by aoflus** [comment]
He realizado una pequeña batería de pruebas del juego, de ello han surgido los siguientes puntos:
- Los cerdos siguen andando del revés aun teniendo los ejes reseteados. Además no se ha cargado correctamente una de las texturas. (Hablando con el Team B se ha visto que es un problema de los modelos de blender. Hay que reimportar algunos de ellos -foto-).
![imagen](https://cloud.githubusercontent.com/assets/11500214/20719178/76a9770a-b65b-11e6-902b-91ebb590973e.png)

- Las torres tienen un delay de unos 15 segundos desde que empieza la partida antes de que empiecen a atacar (Las torres no detectan a los enemigos "gordos" como enemigos; el Team B ya está trabajando en ello ;) ).

- Las torres no siempre se giran hacia el objetivo al que disparan (el tema es algo más complejo; explicación del Team B: Cuando la torre fija un objetivo va rotando para seguirlo, esta operación se ejecuta cada frame. Cada vez que dispara la torre realiza un cálculo de dónde estará el enemigo una vez el proyectil impacte, como es un cálculo más costoso que simplemente mirar al enemigo hemos decidido que se haga cada X segundos (cuando la torre dispara) en vez de cada frame.Si el enemigo está cerca de la torre la diferencia entre la orientación de la torre y la trayectoria del proyectil no debería notarse mucho. En el equipo B ya tenemos pendiente la tarea de hacer que las torres fijen como objetivo al enemigo más cercano).

- Tras la tercera wave completa, el juego se queda "bugueado" en un estado de -1 (el motivo que sugiere el Team B es que tal vez sólo haya 3 waves en el xml, y por tanto al acabar la tercera, el juego se queda en este estado, pero habría que confirmarlo).
![imagen](https://cloud.githubusercontent.com/assets/11500214/20719833/709c6c94-b65d-11e6-876f-6806e533ee82.png)


Por el resto, yo lo he visto todo correcto. Sólo comentar que aun no hay "Game Over" implementado, pero hay un issue creado en este sprint por parte del Team C para este objetivo.

Por lo demás, todo perfecto!
![imagen](https://cloud.githubusercontent.com/assets/11500214/20719452/3b813054-b65c-11e6-9649-806e3ce1ea51.png)

**Comment by sdiaz7** [comment]
Los cambios se han integrado correctamente y ahora DEV vuelve a ser funcional. Issue DONE.

**Comment by agonzatr17** [comment]
Además de lo ya comentado por el compañero _aoflus_, dejo aquí mi **review de Bugs** y/o correcciones a hacer (lo escribo aquí para tener constancia de los diversos bugs que se han encontrado y que en la continuación del sprint se consideren):

**TowerPlacement**:
- La torre no debería colocarse si se hace click cuando el raton está sobre el HUD superior (con el HUD inferior ya funciona bien)
- No debería poder bloquearse el camino de los enemigos poniendo torres (aunque ahora mismo si un enemigo se queda bloqueado, al cabo de unos segundos, destruye las torres que más cerca tiene).

**Enemy counter (HUD superior)**: 
- Los enemigos que llegan a la torre central también deberían descontar el número de enemigos restantes que hay en el HUD inferior (por lo visto solo los que matan las torres descuentan). 
- Además el número no está bien definido, se sobreponen carácteres.
![sprint4_HUD_enemies](https://cloud.githubusercontent.com/assets/11499646/20800506/03c3f364-b7e6-11e6-98fb-4f7770813b46.png)


**Texturas/modelos**:
- Los proyectiles (algunos) salen desde muy abajo de la torre y van atravesando el terreno (a pesar de ser imperceptible desde el punto de vista del jugador, pero si se pausa se puede ver).
![sprint4_textura_proyectil](https://cloud.githubusercontent.com/assets/11499646/20800468/e584cb9e-b7e5-11e6-8671-e10e80b87305.png)
- Añadir modelos para los distintos tipos de proyectiles y sus respectivas texturas.
