### ISSUE TITLE
Improve the turrets.

### ISSUE THREAD

**Issue by sgarriga10** [NestorTejero/ES2016A#134]

**Comment by sgarriga10** [comment]
Definition of done:
-Small modification of the structure of the aircraft and its texture.
-Improve the base of the plane with a less rectangular shape and change the texture.

**Comment by carlosarenasf** [comment]
Definition of done:
·Modify design for tank 
·Add new texture
·Improve design of base

**Comment by NestorTejero** [comment]
@sgarriga10 , @charlyhook , @ezendirak  no entenc perquè hi ha issues assignades a més d'una persona. Si surten així, descomposeu-les perquè cadascú pugui treballar per separat.

**Comment by sgarriga10** [comment]
@NestorTejero Las hice así porque me fije en el trabajo realizado por los antiguos scrum master y hasta ahora se habia hecho así en caso de tener una misma issue para 3 personas diferentes.

**Comment by sgarriga10** [comment]
Está issue ya ha sido separada individualmente.

**Comment by NestorTejero** [comment]
@sgarriga10 gràcies! Fall meu de no haver vist els casos on havia passat el mateix.
