### ISSUE TITLE
Create new enemies.

### ISSUE THREAD

**Issue by sgarriga10** [NestorTejero/ES2016A#135]

**Comment by sgarriga10** [comment]
Definition of Done: 
-The enemy will be finished when you have the structure, textures and animations of movement and attack created and integrated.

**Comment by carlosarenasf** [comment]
Definition of done:
·Make a new enemy
·Add texture 
·Add animation attack and walk

**Comment by sgarriga10** [comment]
Esta issue ya ha sido separada individualmente.
