### ISSUE TITLE
Create a final boss.

### ISSUE THREAD

**Issue by sgarriga10** [NestorTejero/ES2016A#136]

**Comment by aoflus** [comment]
Definition of done for the issue:
- Make a final boss model.
- Add the textures.
- Add the animations.
- Test in a closed environment.
- Deploy on the project.

**Comment by aoflus** [comment]
![final boss](https://cloud.githubusercontent.com/assets/11500214/20642249/33fa7d12-b40a-11e6-8e2f-d2b37f9bbb66.jpg)
First design of the final boss.

**Comment by aoflus** [comment]
![final boss](https://cloud.githubusercontent.com/assets/11500214/20642545/d49015dc-b411-11e6-9d01-1578a3760e0a.jpg)

The first design resembled too much to the already created big caveman, so I have made a total concept redesign.

**Comment by aoflus** [comment]
![imagen](https://cloud.githubusercontent.com/assets/11500214/20674030/9d097762-b587-11e6-8d41-46bff42ab0a3.png)
I have had several problems with the model. I had a model with armature already done, but while animating the meshes deformed in a very weird form, so I have decided to do some changes on the model.

**Comment by aoflus** [comment]
The issues still persisted, so I have re-done the model from scratch. (4h).
I am working on the armature and animations at the moment. I guess it will take me 3 to 6 hours, depending on the amount of difficulties.
I have already had some issues with the armature, mainly because it is a bit complicated merging two diferent models with thir own armatures into one.

**Comment by aoflus** [comment]
Added some details to the caveman mesh. (1h)
Added the bone structure. (1h)
Corrected the bone weights, meshed all the bone structures into one. (6h)
Created a cane mesh. (1h).

This is the actual progress.
![imagen](https://cloud.githubusercontent.com/assets/11500214/21293216/eb5157f0-c51d-11e6-929b-4a39153970f7.png)
