### ISSUE TITLE
Animation for the death of enemies

### ISSUE THREAD

**Issue by sgarriga10** [NestorTejero/ES2016A#137]

**Comment by carlosarenasf** [comment]
Definition of done:

·Make design of coin for enemies death animation
·Add textures

**Comment by carlosarenasf** [comment]
Muestra de avances

![capturacoin](https://cloud.githubusercontent.com/assets/11389074/20985378/84762e2c-bcc4-11e6-8e99-ea3bb1df6953.PNG)

**Comment by carlosarenasf** [comment]
PR #212

Se ha creado una moneda para la animación de la muerte de los enemigos, se ha dado textura.
Se ha integrado correctamente y funciona bien.

Tiempo de trabajo 1h
