### ISSUE TITLE
Initial presentation.

### ISSUE THREAD

**Issue by sgarriga10** [NestorTejero/ES2016A#138]

**Comment by nicofo** [comment]
Definition of done for the issue:

1. Create a Blender scene and integrate all the elements.
2. Make a blocking animation
3. Define the camera
4. Make a more accurate animation
5. Lightning and composition
6. Postproduction

**Comment by nicofo** [comment]
Integration of models
![captura2](https://cloud.githubusercontent.com/assets/11062934/21074876/51e76790-bf04-11e6-852b-7e42652466f5.PNG)
![captura1](https://cloud.githubusercontent.com/assets/11062934/21074877/56f49b86-bf04-11e6-90ca-a179461dada5.PNG)

**Comment by nicofo** [comment]
La animacion va avanzando.
Se ha integrado el cerdo.
Mejoras respecto a la iluminación con un HDR.
En las proximas horas subire algun video, a la espera estoy del Render.
![untitled](https://cloud.githubusercontent.com/assets/11062934/21164051/042c4cf6-c197-11e6-9c06-87948a62c8db.png)
![untitled1](https://cloud.githubusercontent.com/assets/11062934/21164054/062aae9e-c197-11e6-9cd4-246deb51c13f.png)
![untitled2](https://cloud.githubusercontent.com/assets/11062934/21164058/08b95250-c197-11e6-8eb1-1a0dd1d03d62.png)
![untitled3](https://cloud.githubusercontent.com/assets/11062934/21164059/0a72e962-c197-11e6-96f6-980f3fecef2a.png)

**Comment by nicofo** [comment]
Actualmente tengo 2 versiones. Una con el cavernicola gordo y otra sin.
Espero feedback para esta tarde tirar render en alta calidad.

https://youtu.be/d73fSUKjr3k
https://youtu.be/gTHrFo1TMbw

Hay un error con los gordos en la malla, por eso no se si mantenerlos.

**Comment by nicofo** [comment]
He fet millores en el montatje del audio
https://www.youtube.com/watch?v=ETrx4HnaFFk&feature=youtu.be

**Comment by nicofo** [comment]
Per slack m'han donat per bona l'ultima versió feta. He començat a fer render i per dema al mati estara.

**Comment by nicofo** [comment]
Después de 14 horas de render y 1 hora de fix. Tengo una versión final con un poco más de resolución.

**Comment by nicofo** [comment]
pull request fet y acceptat
