### ISSUE TITLE
Create new projectiles

### ISSUE THREAD

**Issue by sgarriga10** [NestorTejero/ES2016A#139]

**Comment by vmganela** [comment]
1. Corregir normales de proyectile-missile.
2. Creacion de nuevos proyectiles.
3. Respetar el naming convention.
4. Respetar Game Measures.
5. Comprobar que en el juego no hay problemas de normales.
6. Comprobar que la exportacion esta bien.

**Comment by vmganela** [comment]
![bullet](https://cloud.githubusercontent.com/assets/6916126/20757811/05ff27f8-b718-11e6-8a94-cf234bad641e.png)
![missile2](https://cloud.githubusercontent.com/assets/6916126/20757810/05edd75a-b718-11e6-9dea-ff204a8de130.png)
![boomerang](https://cloud.githubusercontent.com/assets/6916126/20757812/0613ff52-b718-11e6-80fd-1f2751b96cfa.png)
![spear](https://cloud.githubusercontent.com/assets/6916126/20757813/061597a4-b718-11e6-8945-7f2226612dcd.png)

**Comment by Nerucius** [comment]
Que salto de calidad, si señor. Aun veo alguna cara asi con shading *curioso*, puede que de normales o de vertices no fusionados, sobretodo en la "bala", pero en general estan muy bien

**Comment by vmganela** [comment]
Los modelos estan correctamente subidos al proyecto.
Se ha seguido las convenciones del naming del proyecto.
Se ha tratado de que sus tamaños sea correctos y adecuados (nadie ha reportado quejas)

Tiempo: 7h
