### ISSUE TITLE
TowerSelection system bug

### ISSUE THREAD

**Issue by agonzatr17** [NestorTejero/ES2016A#158]
It was commented in the issue [https://github.com/NestorTejero/ES2016A/issues/91](https://github.com/NestorTejero/ES2016A/issues/91) and in the pull request [https://github.com/NestorTejero/ES2016A/pull/122](https://github.com/NestorTejero/ES2016A/pull/122)

**User story**: when clicking to place a tower, if there is a tower in the mouse way it also selects that tower (the tower is correctly placed).

**Definition of DONE**: while tower placing, the player will not be able select any tower for the purposes of selling or upgrading it. When the tower is placed or the placement is cancelled the player can select towers again.

**Comment by sdiaz7** [comment]
Implementation tested and merged.
