### ISSUE TITLE
Change character rotations

### ISSUE THREAD

**Issue by aoflus** [NestorTejero/ES2016A#160]
![imagen](https://cloud.githubusercontent.com/assets/11500214/20802346/0d78887e-b7ec-11e6-9c23-234145e5ebbb.png)
The red marked models need to have its rotation changed, so when the team B integrates them in the game, they perform correctly,

**Comment by aoflus** [comment]
Definition of done: 
* Test on a unity project that the models are looking the right direction.
* To do so, rotate little by little the meshes on blender unitl they look right.

**Comment by sgarriga10** [comment]
En esta issue no se me deberia haber asignado porque mis modelos estaban correctos.

Por mi parte esta issue está done.

**Comment by nicofo** [comment]
Por mi esta done. Ya me separe la issue y la complete. #198

**Comment by ezendirak** [comment]
Está hecho en #155

**Comment by aoflus** [comment]
Issue completada.
