### ISSUE TITLE
Define tower upgrades

### ISSUE THREAD

**Issue by sdiaz7** [NestorTejero/ES2016A#163]
Define each upgrade level as a stats improvement. Store such information in an xml and make it accessible for upgrading logic.

RECOMMENDATION: Wait for issue #161 to be done, because it might add a new tower stat (rotation speed).

**Comment by agonzatr17** [comment]
New xml file storing stats of the different Towers. There are 2 possible upgrades for each tower (3 levels each one). As recommended, we waited for the new tower stat (rotation speed) and defined it too.

**Pull Request #197**
