### ISSUE TITLE
Add particle effects when enemies get hit

### ISSUE THREAD

**Issue by sdiaz7** [NestorTejero/ES2016A#166]
Add particle effects when enemies get hit by a projectile.

**Comment by AitoreMePe** [comment]
Definition of Done
- When a enemies get a hit, a particle effect of blood appear.
- When enemies die, the particle disappear.

**Comment by AitoreMePe** [comment]
![image](https://cloud.githubusercontent.com/assets/4471562/20971037/4c88a10e-bc90-11e6-8c89-140cd1e1edea.png)

**Comment by AitoreMePe** [comment]
Creado el prefab

**Comment by sdiaz7** [comment]
Tal como quedamos, he subido la integración del Hit prefab en el EnemyBehavior. He aumentado un poco el tamaño del prefab para que pueda apreciarse mejor el efecto. El objeto hit se instancia en la misma posición del proyectil (es decir, en el punto de impacto) y usa la misma dirección y sentido que este para propagarse. El objeto se autodestruye pasado 1 segundo.

**Comment by sdiaz7** [comment]
Pull requested accepted and merged. Issue closed and moved to DONE
