### ISSUE TITLE
Implement score

### ISSUE THREAD

**Issue by sdiaz7** [NestorTejero/ES2016A#167]
Implement some mechanism to store a score the player recieves for killing enemies and/or clearing a round. Make such score accessible for team C.

**Comment by mgonzafe91** [comment]
DoD: Recoger datos estadísticos de la partida para mostrar al finalizarla.

Los datos serán:
- Rondas superadas (+100 puntos/ronda)
- Enemigos derrotados (+1 punto/enemigo)
- Torres construidas
- Torres vendidas
- Oro conseguido
- Tiempo de partida
- Puntuación total

**Comment by mgonzafe91** [comment]
Ya guarda los valores mencionados en el comentario anterior.

Falta conectar los siguientes métodos con el LogicConnector (Team C):

- ControlWaves.cs (al ganar la partida)
![image](https://cloud.githubusercontent.com/assets/9026825/20904361/6a5a9ffe-bb3f-11e6-9c74-2c284d9c6c90.png)
*Enviar getters al LogicConnector y llamar el método para cambiar a la escena de victoria (no existe)

- HomeBehaviour.cs (al perder la partida)
![image](https://cloud.githubusercontent.com/assets/9026825/20904380/8afdde88-bb3f-11e6-90a2-3861f2fc0ae1.png)
*Enviar getters al LogicConnector

**Comment by sdiaz7** [comment]
Implementation satisfies the definition of done, and has been merged into DEV. I proceed to close the issue and move it to DONE.
