### ISSUE TITLE
Repair waterfall particle animation

### ISSUE THREAD

**Issue by sdiaz7** [NestorTejero/ES2016A#168]
**Pull request #185**

**Comment by AitoreMePe** [comment]
Definition of Done
- Reintegrar las particulas de animación de la cascada para dar un mayor dinamismo a la esce3na

**Comment by AitoreMePe** [comment]
![image](https://cloud.githubusercontent.com/assets/4471562/21138908/aaf853c0-c130-11e6-9eb9-6b705554571a.png)
