### ISSUE TITLE
Create terrain obstacles

### ISSUE THREAD

**Issue by sdiaz7** [NestorTejero/ES2016A#169]
### Definition of Done:

- Create terrain obstacles so that enemy trajectories are less linear
- Possible objects include:
  - Ruined buildings
  - Stone structures (Dolmen / Menhir)
  - Big rocks

**Comment by AitoreMePe** [comment]
![image](https://cloud.githubusercontent.com/assets/4471562/21104882/77faf57a-c088-11e6-8f02-fb69e7a16df3.png)
versión para implementar en unity

**Comment by AitoreMePe** [comment]
![image](https://cloud.githubusercontent.com/assets/4471562/21105057/2ec668de-c089-11e6-9964-58dc5f085b82.png)
Stonehenge real

**Comment by AitoreMePe** [comment]
![image](https://cloud.githubusercontent.com/assets/4471562/21105996/a5970f7e-c08c-11e6-943b-cde0a7f7ac4b.png)
Dentro de Unity, falta agregar colisión.

**Comment by AitoreMePe** [comment]
![image](https://cloud.githubusercontent.com/assets/4471562/21138832/34eba858-c130-11e6-8a54-d8ba431d9bb0.png)
Ahora ya esquiva las torres

**Comment by sdiaz7** [comment]
Pull requested accepted and merged. Issue closed and moved to DONE.
