### ISSUE TITLE
Assign different projectiles to each tower

### ISSUE THREAD

**Issue by sdiaz7** [NestorTejero/ES2016A#171]
### Definition of Done
- Different towers use different projectile prefabs
- Projectiles are to scale, visible to the player but not exceedingly big.
- Projectile mode is correctly rotated when shot

**Estimated 4 Hours**

Possible dependencies: #170

**Comment by Nerucius** [comment]
Done on the same branch as #170 
Pull request at #184

**Comment by sdiaz7** [comment]
Implementation satisfies the definition of done, and has been merged into DEV. I proceed to close the issue and move it to DONE.
