### ISSUE TITLE
Integrate attack animations

### ISSUE THREAD

**Issue by sdiaz7** [NestorTejero/ES2016A#181]
Integrate attack animations into the new Enemy Behaviour. 

### Definition of DONE:
- Enemies display a characteristic animation while attacking.
- Each enemy prefab has its own distinctive animation.

This issue condensates and redefines tasks placed at #165 , #66 and #67 . Assignees moved to this new issue.

Branch: [dev_Issue181](../tree/dev_Issue181)

Time estimated: 2 hours

**Comment by sdiaz7** [comment]
As provided by @Nerucius , this line of code might be useful for implementing attack animation:

`GetComponent<Animator>().SetTrigger("atack");`

**Comment by Nerucius** [comment]
**Status report**
Due to the latest developments of 'EnemyBehavior` all that is left of this issue is trigger the animation when atacking and triggering back walking when done attacking.

**Comment by sdiaz7** [comment]
Since I am working on enemy scripts and prefabs, I am going to fix enemies not looking to the target when spawned.

**Comment by sdiaz7** [comment]
Attack animation is now displayed once the enemy starts attacking. Oddly, the animation coexists with the walking one through the attack. I am currently investigating why this is happening.

**Comment by sdiaz7** [comment]
To ensure that animator stays in a state of animation for an undefined period of time, the controller's transitions have to look something like this:
![image](https://cloud.githubusercontent.com/assets/17719241/21023516/270cf9e2-bd81-11e6-94f3-cd88e607c568.png)

**Comment by sdiaz7** [comment]
Pull request opened for review: #191

**Comment by sdiaz7** [comment]
Pull request accepted and merged into DEV. Issue closed and moved to DONE.
