### ISSUE TITLE
Improve the turrets.

### ISSUE THREAD

**Issue by sgarriga10** [NestorTejero/ES2016A#214]
Definition of done:
-Small modification of the structure of the aircraft and its texture.
-Improve the base of the plane with a less rectangular shape and change the texture.

**Comment by sgarriga10** [comment]
Se ha creado correctamente la base simulando el arco del triunfo de Barcelona para seguir un poco también la temática que dijo Nestor de introducir elementos de Barcelona y se ha aplicado correctamente la textura. 

También se ha añadido al avión un efecto estético(6h).

**Comment by NestorTejero** [comment]
Bona feina, @sgarriga10  Que hi ha pull request? Enllaça-la per fer més fàcil el seguiment, gràcies.

**Comment by sgarriga10** [comment]
@NestorTejero  Te he mencionado en el PR creado para esta issue, que no se porqué aparece el número 215 en lugar del 214 al cual corresponde esta issue. La rama creada tambien está señalada la issue 214.

**Comment by mgonzafe91** [comment]
#215 Con poner esto es suficiente, nunca te va a coincidir el número de issue con el de PR porque básicamente no se puede repetir el identificador

**Comment by sgarriga10** [comment]
@kazusaki1 Vale gracias! lo tendré en cuenta! Para los siguientes!

**Comment by NestorTejero** [comment]
@kazusaki1 exacte, les issues i els PR utilitzen la mateixa variable per identificar-les. De fet si vas a https://github.com/NestorTejero/ES2016A/issues/215 et redirigeix a `/pull/215`.
I sí, utilitzant `#` + el número ja es fa l'enllaç.
