### ISSUE TITLE
Draw an area marker for the Range of a turret

### ISSUE THREAD

**Issue by Nerucius** [NestorTejero/ES2016A#226]
### Definition of Done
- A marker on the ground is displayed while placing a turret, indicating how far it can shoot
- This marker must disappear when the turret is placed

**Estimate 2 Hours**

**Comment by Nerucius** [comment]
Pull request at #227

**Comment by sdiaz7** [comment]
Branch merged into DEV after approval. Issue closed and moved to DONE.
