### ISSUE TITLE
Crear Enemigo Neandethal

### ISSUE THREAD

**Issue by vmganela** [NestorTejero/ES2016A#229]
Está issue se ha creado tarde, pero el contenido y el trabajo sobre el que va la issue está hecho.

En esta issue se debe crear un nuevo enemigo.
Tiene el tamaño estipulado según lo acordado en clase.
Se respeta la metodología de nombres.
Se ha exportado correctamente.
Se ha revisado que la orientación fuera correcta.
Se han hecho 2 animaciones caminar y atacar
Se ha revisado que disponga de dos animacion en la exportacion

Tiempo de trabajo 7h

**Comment by vmganela** [comment]
Todo los relacionado con las imagenes esta en el pull request de neandethal

**Comment by agonzatr17** [comment]
Pongo link del pull request: #201

**Comment by agonzatr17** [comment]
Añade el issue al kanban del project de tu equipo (y asignalo aquí también) que así se verá el trabajo hecho.
