### ISSUE TITLE
Crear y mejorar texturas de sangre

### ISSUE THREAD

**Issue by vmganela** [NestorTejero/ES2016A#233]
Las anteriores texturas subidas no cumplían con una serie de requisitos

**Comment by ezendirak** [comment]
Textura añadida en (Assets\Resources\Textures\Terrain\blood.png) y probada en unity en un plano en fade y escala 0.25:

![bloodonground](https://cloud.githubusercontent.com/assets/17324835/21276005/c34772b6-c3cf-11e6-8825-571e43cb2bd4.PNG)


Se comparte rama con el grupo B para la inegración de la textura en un prefab en la issue #257
