### ISSUE TITLE
Torre de piedra Upgrade

### ISSUE THREAD

**Issue by vmganela** [NestorTejero/ES2016A#237]
Crear Texturas de nivel

**Comment by ezendirak** [comment]
Definition of done: Conseguir tenir 3 textures diferents per indicar el contexte. Una inicial de fusta i les altres dos de roca.

**Comment by ezendirak** [comment]
He ido probando texturas y las que mejor resultado me han dado en unity son estas dos:

![tower-piedra1](https://cloud.githubusercontent.com/assets/17324835/21296746/02f62516-c573-11e6-81a4-0e74a0b10ad2.jpg)
![tower-piedra2](https://cloud.githubusercontent.com/assets/17324835/21296747/0317ff56-c573-11e6-86f5-76e4d3efeb28.jpg)

Las he llamado tower-piedra1 y tower-piedra2. Serían para los 2 primeros niveles de upgrade, y para el último la textura actual.

![image](https://cloud.githubusercontent.com/assets/17324835/21296782/a04cbb90-c573-11e6-9cfe-c4e70fd0c176.png)
