### ISSUE TITLE
Integrate kid model.

### ISSUE THREAD

**Issue by mgonzafe91** [NestorTejero/ES2016A#238]
This issue will be adressed on the same branch as #258 to avoid bloating the repository with branches and pull requests.
Only one new model will be integrated.

**Definition of done:**
- [x] kid model integrated into a new enemy prefab

**Branch:** [dev_enemies](../tree/dev_enemies)

**Estimated time:** less than 1 hour

**Pull request:** #295

**Comment by sdiaz7** [comment]
Branch merged into DEV. Issue closed and moved to DONE.
