### ISSUE TITLE
Avion upgrade

### ISSUE THREAD

**Issue by vmganela** [NestorTejero/ES2016A#239]
Mejorar modelo del avion y su textura para los upgrade

**Comment by sgarriga10** [comment]
Definition of Done:

- Realizar una modificación significativa en la textura de la torre avión,  de tal manera que parezca un modelo nuevo.

**Comment by sgarriga10** [comment]
Se ha completado correctamente la modificación visual de la torre "avión" generando 3 modelos diferentes tal y como se puede ver en el PR #261. (4h)
