### ISSUE TITLE
Game balance.

### ISSUE THREAD

**Issue by mgonzafe91** [NestorTejero/ES2016A#241]
Prerequesite: #238 Integrate enemy models
Check #228 

#241 #249 Se realizarán en la rama dev_Issue241

**Estimation of time:** 8 hour

**Comment by agonzatr17** [comment]
Add the implementations you see necessary to **balance the game.**

**Definition of DONE**:
- [x] Correlation between **Towers damage+firerate** and **Enemies health**.
- [x] Adjust **initial money** and **money per enemy killed**: less initial money but more enemy kill rewards so you can upgrade towers.
- [x] **More rounds** or enemies (more time to play).
- [ ] ...

**Comment by mgonzafe91** [comment]
Modificaciones:
- Colliders de las torres
- Oro extra al acabar la ronda (Nº ronda superada * 100)
- Ajustar el oro inicial a 500
- Modificar el tiempo de espera entre oleadas de enemigos diferentes (dentro de una misma ronda)
- Modificar Xml de torres (stats de cada torre/upgrade)
- Modificar Xml de enemigos (stats de cada enemigo/ronda)

**Comment by Nerucius** [comment]
### Status Update

More info and merged pull request at #296
