### ISSUE TITLE
Design a wall model.

### ISSUE THREAD

**Issue by mgonzafe91** [NestorTejero/ES2016A#243]

**Comment by AitoreMePe** [comment]
DoD: Crear un muro para poder ser integrado como empalizada en el terreno.

**Comment by AitoreMePe** [comment]
![image](https://cloud.githubusercontent.com/assets/4471562/21288274/28319b8e-c47f-11e6-9996-9dc5ab78865e.png)
Versión estable, sujeta a cambios. Se puede integrar ya.
