### ISSUE TITLE
Implement Tower rotation while placing

### ISSUE THREAD

**Issue by mgonzafe91** [NestorTejero/ES2016A#244]
### Definition of done
- While placing a tower, and only while placing, the user can:
  - Rotate the tower using mousewheel, the rotation should occur along the vertical Y axis.
  - Camera zoom gets disabled.

This will allow players to place walls and towers in different directions, to redirect the flow of enemies.

**Estimated time:** 1 hour

**Branch:** [dev_Issue244](../tree/dev_Issue244)

**Pull request:** #271

**Comment by agonzatr17** [comment]
issue done, see pull request #271 for more information
