### ISSUE TITLE
Cavernicola con Maza

### ISSUE THREAD

**Issue by vmganela** [NestorTejero/ES2016A#247]
Hacer que este modelo se pueda integrar en el juego

**Comment by sgarriga10** [comment]
Doy la issue por acabada ya que no he podido finalizar satisfactoriamente esta issue. Esta issue fue asignada en el sprint anterior como "tarea extra" por si acababamos las issues anteriores.

No soy capaz de solucionar un bug por el cual hace que no se vea correctamente cuando se importa a unity y al ser este sprint tan corto no puedo finalizar la tarea, por la cual se cierra y no se añadirá al producto final.
