### ISSUE TITLE
Baby cavernicola

### ISSUE THREAD

**Issue by vmganela** [NestorTejero/ES2016A#248]
Hacer que este modelo se pueda integrar en el juego

**Comment by carlosarenasf** [comment]
Definition of done

-Solve animation bug
-Complete animation to walk and attack

**Comment by aoflus** [comment]
Hablé con Carlos, se hizo pull request aprobado de la issue, pero quedó abierta. Cerrando.

**Comment by NestorTejero** [comment]
#277
