### ISSUE TITLE
Integrate new Columbus tower models

### ISSUE THREAD

**Issue by sdiaz7** [NestorTejero/ES2016A#250]
Integrate the new models, displaying different states of damaged Columbus tower, into the redefined HomeBehavior (see issue #172).

**Prerequisite:** #172

**Definition of Done:** Columbus tower's aspect changes to a more damaged view after some thresholds of damage have been reached. As in #172, the number of thresholds is defined by the number of models integrated.

**Estimation of time:** 1 hour

**Branch:** [dev_Issue250](../tree/dev_Issue250)

**Pull request:** #270

**Comment by sdiaz7** [comment]
Since some model parameters must be corrected by manipulating object's parameters, the time estimated for the issue to be done has increased to 1 hour.

**Comment by eslizon13** [comment]
El usuario recibe el feedback de ver como la torre va pasando por diferentes estados de daño.
A continuación se muestran una serie de capturas donde podemos apreciar los diferentes estados.
![normal](https://cloud.githubusercontent.com/assets/4471562/21288741/e0e43762-c48a-11e6-892b-7f322fc0c92f.PNG)
Estado inicial.
![2](https://cloud.githubusercontent.com/assets/4471562/21288743/ecefb716-c48a-11e6-9977-ad19f158804c.PNG)
![3](https://cloud.githubusercontent.com/assets/4471562/21288744/efb7e180-c48a-11e6-8393-e68ec5b5e242.PNG)
![4](https://cloud.githubusercontent.com/assets/4471562/21288745/f59e5426-c48a-11e6-8cc5-390d12e8e9f8.PNG)
Los diferentes estados.
