### ISSUE TITLE
Review enemy prefabs (colliders, navmeshes).

### ISSUE THREAD

**Issue by mgonzafe91** [NestorTejero/ES2016A#258]
Ensure that existing enemy prefabs have all its components, and check if such components are well placed. This issue will be adressed on the same branch as #238 to avoid bloating the repository with branches and pull requests.

**Definition of Done:**
- [x] Fix enemy-porky texture
- [x] Fix enemy-porky navmesh agent
- [x] Fix enemy-porky collider
- [x] All enemy rigid bodies set as kinematic
- [x] All enemy rigid bodies without gravity
- [x] All enemy prefabs have their components placed correctly

**Branch:** [dev_enemies](../tree/dev_enemies)

**Estimation of time:** 1 hour

**Pull request:** #295

**Comment by sdiaz7** [comment]
Issue ready for review. Waiting for #238

**Comment by sdiaz7** [comment]
Branch merged into DEV. Issue closed and moved to DONE.
