### ISSUE TITLE
Implement wall logic

### ISSUE THREAD

**Issue by sdiaz7** [NestorTejero/ES2016A#268]
Implement wall behavior. For simplicity, it should be a subtype of TowerBehavior.

**Definition of Done:**
- Wall logic stored in a script.
- Script contains wall price and wall health.
- Wall can be attacked by enemies.
- Wall purchase supported.
- Tower interface supports wall.

**Estimation of time:** 2 hours

**Branch:** [dev_Issue268](../tree/dev_Issue268)

**Pull request:** #278

**Comment by sdiaz7** [comment]
Enemy attacking a wall (or praising the sun)

![image](https://cloud.githubusercontent.com/assets/17719241/21289811/9010a944-c4a6-11e6-9f40-df80e04fe35b.png)

**Comment by sdiaz7** [comment]
Wall breached!

![image](https://cloud.githubusercontent.com/assets/17719241/21289816/ac079766-c4a6-11e6-94aa-8a4153c50a5a.png)

**Comment by sdiaz7** [comment]
A small, easy,  maze for the enemies to solve:

![image](https://cloud.githubusercontent.com/assets/17719241/21289865/39cbcb66-c4a8-11e6-98cd-2e6b641884aa.png)

Enemies traversing the maze:

![image](https://cloud.githubusercontent.com/assets/17719241/21289872/5a735a1e-c4a8-11e6-8837-737687469714.png)

![image](https://cloud.githubusercontent.com/assets/17719241/21289878/72e3a554-c4a8-11e6-8152-94163da8db7b.png)

**Comment by sdiaz7** [comment]
Wall purchase supported by the GUI:
![image](https://cloud.githubusercontent.com/assets/17719241/21290722/74c44780-c4c5-11e6-9072-65f0ced41a77.png)

**Comment by sdiaz7** [comment]
The original DoD conflicted with issue #246 because wall was not being supported by tower interface. During the first pull request (#273) the team decided to extend this issue by adding support to wall interface.

New pull request #278 supports the features already implemented on last PR plus wall interface and wall icon on its purchase button (see issue #245).

**Comment by agonzatr17** [comment]
Issue completed, see more info in #278
