### ISSUE TITLE
Add attack speed to enemies synchronized with animation

### ISSUE THREAD

**Issue by agonzatr17** [NestorTejero/ES2016A#66]
### Definition of Done
- Enemies play their attack animation when they reach the tower instead of dissapearing.
- Can still take damage and die

**Comment by Nerucius** [comment]
Part of the necessary changes were added  on merge #149. Final integration requires triggering the animation by code:  
`GetComponent<Animator>().SetTrigger("atack");`

**Comment by sdiaz7** [comment]
This issue is being redefined and merged into new issue #181
