### ISSUE TITLE
Write the Naming Conventions Wiki page

### ISSUE THREAD

**Issue by Nerucius** [NestorTejero/ES2016A#89]
Escribir la pagina de la wiki que define como vamos a llamar todos a los diferentes assets para no tener casos como:  
modelo_enemigo_a.fbx  
otroModeloGuay.fbx  
UltimoMejorModelo.fbx  

Y etc. para Materiales *(SinNombre001.mat, SinNombre002.mat...)*

@nicofo **[Naming Conventions](https://github.com/NestorTejero/ES2016A/wiki/Naming%20Conventions)**

**Comment by mgonzafe91** [comment]
Done
