### ISSUE TITLE
Create a Turret Selection system to Sell or Upgrade towers. (Only the Selection System)

### ISSUE THREAD

**Issue by Nerucius** [NestorTejero/ES2016A#91]

**Comment by agonzatr17** [comment]
**Definition**: The player is able to select a tower by clicking it. It will display an HUD with its stats and 2 buttons so the player is able to sell or upgrade the selected tower.

**Definition of DONE**:
- The player can select a tower by clicking it.
- The player can sell or upgrade the selected tower by using 2 buttons.

**Comment by agonzatr17** [comment]
Done with some small bugs to check. For more info check pull request [https://github.com/NestorTejero/ES2016A/pull/122](https://github.com/NestorTejero/ES2016A/pull/122)

**Comment by agonzatr17** [comment]
Respective commit: https://github.com/NestorTejero/ES2016A/commit/05d3658c4962e0303b1554ef5c1fba8aed090db5
