### ISSUE TITLE
Sell Currently Selected Tower

### ISSUE THREAD

**Issue by Nerucius** [NestorTejero/ES2016A#92]
Provide the logic to allow the player to sell already existing towers. When selling a tower the game object will be destroyed and the player will recieve some value for doing it. Such value must be proportional to the one the player payed to place the tower. Such proportion will be defined on later sprints, by now it will be sufficient if the logic allows to easily change such proportion (eg change it from outside of this logic script).

Definition of done summarized:
- player can delete specific towers
- logic provides some value for deleting a tower

**Comment by sdiaz7** [comment]
By now, the code implemented allows to delete one (and just one) tower by selecting it each time the associated button is clicked. That means that, if the player wants to delete multiple towers he/she has to do it one by one, clicking the button before selecting each tower. This prevents both the delete and place tower logics to get mixed. 

In the coming days I want to implement the value returned for deleting a tower, and some sort of coloration system to make explicit if a game object can be sold or not.

**Comment by sdiaz7** [comment]
Object coloration has proved more complex than I expected, so I've abandoned the idea for this sprint. The feature might be further explored after recieving the product owner's feedback.

**Comment by sdiaz7** [comment]
Implemented code has been pushed into a new branch. The issue will stay in Review by now, since I want team C to confirm that it provides what they need to integrate the feature in their GUI.

**Comment by Nerucius** [comment]
suggestion for drawing object outline:

http://answers.unity3d.com/questions/60155/is-there-a-shader-to-only-add-an-outline.html

**Comment by sdiaz7** [comment]
Issue moved to DONE. It will be closed once the pull request has been accepted.
