### ISSUE TITLE
Upgrade Currently Selected Tower

### ISSUE THREAD

**Issue by Nerucius** [NestorTejero/ES2016A#93]

**Comment by agonzatr17** [comment]
With the bugs in the latest commits we prioritized fixing these bugs. This issue will be done in next Sprint.

**Comment by agonzatr17** [comment]
The player is able to upgrade a tower by selecting it and clicking the "upgrade" button. 

**Definition of DONE:**

- The player can upgrade the selected tower by using a button.
- The upgraded tower becomes stronger (fire rate, damage) or improves other characteristics (range, turn speed) 

It would be interesting to display an HUD with the tower stats, including actual level, and putting the upgrade/sell buttons (from tower selection) inside that HUD (propose this features to Team C).

**Comment by agonzatr17** [comment]
Here are the changes to each file:

**xml file** 
- added a new value "projectilespeed"
- changed health values for more game balance (balance issue yet to be done)
- all the stats values are floats (except cost)

**towerselection script**
- implemented the upgrade tower button: it uses the xml file to update the tower stats
- new method (setTowerVariables) to load some tower variables (name, level, tower levels node in xml, upgrade cost) before showing the buttons (if the tower is not upgradable the button text says "no upgrades", else it shows "UPGRADE X" where X is the upgrade cost)
- problems i had: 
> Getting the right path to the elements i needed:
```
// Selecting all the Level elements of the tower with name towerName
towerNode = root.SelectNodes("(Towers/Tower[@name='" + towerName + "']/Level)");
```
> towerLevel index works as a list 0,1,2... and not using the xml element's id 1,2,3... For example, torre-piedra has 3 levels (with id 1, 2, 3) and to access to the level with id 1 we have to use an index 0, rather than using the id of the level!
```
// Getting the cost value of the towerNode selected with an
// id level towerLevel+1 (so we use the index towerLevel as commented)
upgradeCost = Int32.Parse(towerNode[towerLevel]["cost"].InnerText);
```
```
<Tower name="torre-piedra">
	<Level id="1">
		<range>20.0</range>
		<health>15.0</health>
		<cost>100</cost>
		<damage>6.0</damage>
		<firerate>1.0</firerate>
		<turnspeed>2.0</turnspeed>
		<projectilespeed>15.0</projectilespeed>
	</Level>
	<Level id="2">
		<range>30.0</range>
		<health>15.0</health>
		<cost>50</cost>
		<damage>6.0</damage>
		<firerate>0.5</firerate>
		<turnspeed>2.0</turnspeed>
		<projectilespeed>15.0</projectilespeed>
	</Level>
	<Level id="3">
		<range>40.0</range>
		<health>15.0</health>
		<cost>150</cost>
		<damage>12.0</damage>
		<firerate>0.5</firerate>
		<turnspeed>4.0</turnspeed>
		<projectilespeed>15.0</projectilespeed>
	</Level>
</Tower>
```

> When game ends it might crash if we try to select a tower, so I had to add a try and catch
```
try {
    towerNode = root.SelectNodes("(Towers/Tower[@name='" + towerName + "']/Level)");
}
catch
{
    towerNode = null;
    Debug.Log("ERROR: could not read the xml element with name " + towerName);
}
```

**towerplacement**
- added a name variable to the tower instantiation, with the name of the gameobject (so we know the type of tower we are accessing when selecting and upgrading)
`tow.name = go.name;`

**towerbehavior**
- added a new variable "level" (so we know the actual tower level)
- added setters for the tower variables (to implement the upgrade changes)

**score**
- added a "towersUpgraded" variable to count the number of upgrades done
- added the increment and get methods for this new variable

**Comment by sdiaz7** [comment]
Branch merged into DEV after approval. Issue closed and moved to DONE.
