### ISSUE TITLE
Adjust Economy and ammount of money Enemies give.

### ISSUE THREAD

**Issue by Nerucius** [NestorTejero/ES2016A#94]
To do:

- Provide some ammount of credit to the player so he/she can buy at least one tower when the game starts.
- Adjust the ammount of credit the enemies give after dying.

Done:

- Player has some cash to buy turrets when the game starts. Cash ammount is enough to buy multiple basic towers (dinosaur) but not enough to buy more advanced towers (tank, fighter).
- Once a wave has been completed, player should have been able to obtain enough cash to buy new towers.

**Comment by sdiaz7** [comment]
Though the coding of this issue is very simple, finding the appropriate cash ammount the enemies should give might be complicated. In order to simplify, I am going to assume that towers are properly priced, and fix the enemies value in regarding to such prices.

**Comment by sdiaz7** [comment]
Code already in branch. Still testing cash values

**Comment by sdiaz7** [comment]
Issue moved to REVIEW. I think cash values fit well enough to the current phase of game development. Such values might change as game evolve, though.
I plan to move this issue from REVIEW to DONE tomorrow. Until then, any feedback from fellow programmers/designers is welcomed.

**Comment by sdiaz7** [comment]
Issue will be closed once the pull request has been accepted.
