### ISSUE TITLE
Refine and expand on a new RoundManager System for custom waves.

### ISSUE THREAD

**Issue by Nerucius** [NestorTejero/ES2016A#96]
Must also include public API:
 - Current ROUND Number.
 - Remaining Enemies (in the current round).
 - Total Enemies (in the current round).

**Comment by mgonzafe91** [comment]
more features:
- read enemy/round stats from a xml file

**Comment by mgonzafe91** [comment]
Current state:
- Get remaining enemies (need team C code to test).
- Get total enemies (need team C code to test).
- Get enemy/round stats from a xml.

Miss:
- Current round number (need the name of team C method and code to test). 
**Check if method name is correct!!**

- A team C button must to call NextRound() from ControlWaves (and then test it).

Note: Some lines are commented (in ControlWaves and EnemyBehaviour scripts). Once code has been integrated into dev, uncomment these lines.

**Comment by sdiaz7** [comment]
Logic works finely from the point of view of team B. Since its correctness was already discussed during the mid-sprint meeting, I'm going to move this issue to DONE.
