### ISSUE TITLE
Integrate Tower Models

### ISSUE THREAD

**Issue by Nerucius** [NestorTejero/ES2016A#97]
### Definition of Done
- Turrets use their correct model and not some placeholder
- The model is textured
- The turret constists of 2 parts, a base and a rotating part
- The turrets are to scale in relation to each other and to the enemies

**Comment by Nerucius** [comment]
**Partially done at #161/#162** 
- torre-piedra now using placeholder meshes for the turret part  

**Next steps:**
- Wait for torre-piedra turret part model (the part that rotates)
- Request UV fixing of most turrets
- Create materials and insert into prefabs

**Comment by sdiaz7** [comment]
Branch merged into DEV after approval. Issue closed and moved to DONE.
