### ISSUE TITLE
Integrate Enemy Models

### ISSUE THREAD

**Issue by Nerucius** [NestorTejero/ES2016A#98]
### Definition of Done
- All enemies model ingame + textured
- Correct scale
- Correct animations
- Animation blending for walking -> attack

Branch: [dev_issue98](../tree/dev_issue98)

**Comment by Nerucius** [comment]
Missing enemy models. Can not complete this task.

**Comment by Nerucius** [comment]
**Estimate 6 hours, current problems:**
- missing animations
- Incorrectly exported models (enemies walking sideways)
- missing textures

**Comment by Nerucius** [comment]
**Update:**
- All models now show ingame, correctly scaled
- Orientation is still wrong:
 - Cavernicola walking sideways
 - Porky walking backwards

Can only solve reexporting FBX files, Contacting Team B...

**Comment by Nerucius** [comment]
**Update:**
- Still waiting on fixes from Team A's side:
  - Cavernicola facing sideways
  - Gordo missing animations
  - Porki is backwards

**Comment by Nerucius** [comment]
**Update:**
- Gordo is now 100% functional, with animations and new model/texture as of Pull Request #173 + #184

**Comment by sdiaz7** [comment]
The only new enemy model provided on time has been the neanderthal (#201). Hence, this will be the only new enemy integrated during this sprint.

**Comment by sdiaz7** [comment]
enemy-neanderthal created, with its own animatior controller. New enemy has yet to be tested and included in the round xml files.

**Comment by sdiaz7** [comment]
The rounds xml have been updated to contain neanderthals. By now, they will have the same stats as enemy-gordo. Stats adjustement will be done at issue #192 .

**Comment by sdiaz7** [comment]
A bug implying enemy-cavernicola has also been solved: now the cavernicola can be hurted by projectiles.

**Comment by sdiaz7** [comment]
enemy-neanderthal tested and working as expected. I proceed to open the pull request for [dev_issue98](../tree/dev_issue98)

**Comment by sdiaz7** [comment]
Pull requested accepted and merged. Issue closed and moved to DONE.
